from . import start
from . import trainings
from . import nutrition
from . import progress
from . import premium
from . import trainers
from . import services
from . import reviews
from . import admin
from . import navigation
from . import common